input_fasta: "/path/to/haplotype_seqs_CYP2D6_through_7.fa"
reference_genes: "/path/to/CYP2D6_7_and_8_CHM13_seqs.fa"

kmer_size: 100
minimap2_options: "-x map-hifi -a -Y --eqx -A 2 -B 4"

plot_options:
  main_genes:
    - "CYP2D6"
    - "CYP2D7"
  colors:
    CYP2D6: "gold"
    CYP2D7: "dodgerblue"
    REP6: "pink"
    Spacer: "lightskyblue"
    CYP2D8: "mediumorchid"
    Both: "green"
    None: "lightgray"
    Past_end: "ghostwhite"
  kmer_shape: "â–‰"
  sort_by: "colored_blocks"
  clustered: "false"
